### ISSUE TITLE
After running, there is an error message, but no content has been modified

### ISSUE THREAD

**Issue by CCLLllll** [mayt/BrowserGPT#18]
`BrowserGPT> Input a task
> Go to Wikipedia
Execution failed
TypeError: Cannot read properties of undefined (reading 'data')
    at getPlayWrightCode (file:///Users/wcl/Desktop/Code/GPTBrowser/actions/interactWithPage.js:65:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async interactWithPage (file:///Users/wcl/Desktop/Code/GPTBrowser/actions/interactWithPage.js:8:16)
    at async main (file:///Users/wcl/Desktop/Code/GPTBrowser/index.js:48:9)
BrowserGPT> Input a task
>
`

**Comment by mayt** [comment]
Looks like you may have entered an invalid `OPENAI_KEY`. Did you update your `.env` file with your own key?

**Comment by BaseInfinity** [comment]
Can you try again @CCLLllll? When I use an invalid API key I get a proper error now but when I first played with the repo a month or so back I got a similar error on an API key that was valid but disabled

**Comment by mayt** [comment]
@CCLLllll i'll close this issue if this is no longer an issue.

**Comment by CCLLllll** [comment]
> 看来您输入的内容可能无效`OPENAI_KEY`。您是否`.env`使用自己的密钥更新了文件？

Yes, I found that my OpenAI account balance was insufficient, which led to an error message

**Comment by CCLLllll** [comment]
> @CCLLllll如果这不再是问题，我将关闭此问题。

谢谢你，问题已经解决
