### ISSUE TITLE
The `punycode` module is deprecated

### ISSUE THREAD

**Issue by husamia** [mayt/BrowserGPT#6]
I am getting error message from the command npm run start after I installed all the dependencies 

```


> browser-gpt@1.0.0 start
> node index.js

(node:5836) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launch: Executable doesn't exist at /Users/HFHE/Library/Caches/ms-playwright/chromium-1091/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at main (/Users/HFHE/BrowserGPT/index.js:171:34)
    at /Users/HFHE/BrowserGPT/index.js:212:1 {
  name: 'Error'
}

Node.js v21.2.0
```

**Comment by slavakurilyak** [comment]
Try updating your playwright using `npm install -D @playwright/test@latest`

**Comment by husamia** [comment]
that didn't help but what helped was downgrading npm version to 20

**Comment by pedrhenriqolv** [comment]
@husamia try `npm update && npx playwright install`

**Comment by mayt** [comment]
Does that fixes it for you?

**Comment by husamia** [comment]
Yes, it's fixed. it was the npm version downgrade that did it

**Comment by pedrhenriqolv** [comment]
I'm using the node v21.2.0 and npm 10.2.4

**Comment by mayt** [comment]
Im gonna mark this as resolved then
